@startuml Beziehungsdiagramm
class PdfParser

class JsonParser

class Controller

class AiController

class AiService

class AiAdapter

class ResponseService

Controller -- PdfParser
Controller -- JsonParser
Controller -- AiController
AiController -- AiService
AiService -- AiAdapter
Controller -- ResponseService
ResponseService -- JsonParser
@enduml
