@startuml Klassendiagramm
class PlagiarismCheckResult {
    Author author
    String thesisText
    List<PlagiarismSource> sources
    +addSource(PlagiarismSource)
    +getCoverage(): float
    +getPlagiarismLength(): int
}

class PlagiarismSource extends Source {
    List<PlagiarismOccurrence> occurrences
    +addOccurrence(PlagiarismOccurrence)
    +getPlagiarismLength(): int
}

class PlagiarismOccurrence {
    int start
    int end
    float certainty
    +getPlagiarismLength(): int
}

class Author {
    String name
}

class Source {
    String isbn
    String title
    Author author
}

interface Parser {
    +validate(File)
    +parse(File)
}

class PdfParser implements Parser {
    +validate(File)
    +parse(File)
}

class JsonParser implements Parser {
    +validate(File)
    +parse(File)
    +validateSchema(Schema)
}

class Controller {
    +checkPlagiarism(Thesis, AdditionalData): Json
}

class AiController {
    +checkPlagiarism(Thesis, AdditionalData): PlagiarismCheckResult
}

class AiService {
    +checkPlagiarism(Thesis, AdditionalData): PlagiarismCheckResult
    -generatePrompt(Thesis, AdditionalData): String
    -getPlagiarismCheckResultFromString(String): PlagiarismCheckResult
}

class AiAdapter {
    +chat(String): String
}

class ResponseController {
    +getJsonFromPlagiarismCheckResult(PlagiarismCheckResult): Json
}

class ResponseService {
    Schema jsonResponseSchema
    +getJsonFromPlagiarismCheckResult(PlagiarismCheckResult): Json
}

Controller "1" o-- "1" PdfParser
Controller "1" o-- "1" JsonParser
Controller "1" o-- "1" AiController
AiController "1" o-- "1" AiService
AiService "1" o-- "1" AiAdapter
Controller "1" o-- "1" ResponseController
ResponseController "1" o-- "1" ResponseService
ResponseService "1" o-- "1" JsonParser

PlagiarismCheckResult -- AiController
PlagiarismCheckResult -- AiService
PlagiarismCheckResult -- ResponseService

PlagiarismCheckResult "1" o-- "*" PlagiarismSource
PlagiarismCheckResult "1" o-- "1" Author
PlagiarismSource "1" o-- "1..*" PlagiarismOccurrence
PlagiarismSource "1" o-- "1" Author
@enduml
