@startuml Klassendiagramm
class PlagiarismCheckResult {
    List<PlagiarismSource> sources
    -getPlagiarismCoverage(): int
    +toJson(jsonResponseSchema):
}

class PlagiarismSource {
    String isbn
    List<(int, int)> occurrences
    int coverage
}

interface Parser {
    +validate(File)
    +parse(File)
}

class PdfParser implements Parser {
    +validate(File)
    +parse(File)
}

class JsonParser implements Parser {
    +validate(File)
    +parse(File)
    +validateSchema(Schema)
}

class Controller {
    +checkPlagiarism(Thesis, AdditionalData): Json
}

class AiController {
    +checkPlagiarism(Thesis, AdditionalData): PlagiarismCheckResult
}

class AiService {
    +checkPlagiarism(Thesis, AdditionalData): PlagiarismCheckResult
    -generatePrompt(Thesis, AdditionalData): String
    -getPlagiarismCheckResultFromString(String): PlagiarismCheckResult
}

class AiAdapter {
    +chat(String): String
}

class ResponseController {
    +getJsonFromPlagiarismCheckResult(PlagiarismCheckResult): Json
}

class ResponseService {
    Schema jsonResponseSchema
    +getJsonFromPlagiarismCheckResult(PlagiarismCheckResult): Json
}

Controller "1" o-- "1" PdfParser
Controller "1" o-- "1" JsonParser
Controller "1" o-- "1" AiController
AiController "1" o-- "1" AiService
AiService "1" o-- "1" AiAdapter
Controller "1" o-- "1" ResponseController
ResponseController "1" o-- "1" ResponseService
ResponseService "1" o-- "1" JsonParser

PlagiarismCheckResult -- AiController
PlagiarismCheckResult -- AiService
PlagiarismCheckResult -- ResponseService

PlagiarismCheckResult "1" o-- "*" PlagiarismSource
@enduml
